### ISSUE TITLE
Fix the wikidata reconcilliation

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#10]
The wikidata reconciliation is not working. We need to update the Elastic search with the attached data and make sure the reconciliation uses it. I will start working on this and let you know when I need help. 
[wikidata_2022.zip](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/9971443/wikidata_2022.zip)

**Comment by kalycoding** [comment]
any update here

**Comment by tomersagi** [comment]
Sorry, did not have time to work on it. Will try today.

**Comment by tomersagi** [comment]
Currently running the code to extract wikidata places using Karl's instructions. It takes a few hours to run the first step.

**Comment by tomersagi** [comment]
Wikidata places extracted.

**Comment by kalycoding** [comment]
Great

**Comment by tomersagi** [comment]
I want to fill the elastic search server with the wikidata places I extracted. Which one are you using? the local one you installed on the VM or the elastic cloud service I sent you?

**Comment by kalycoding** [comment]
I’m using the local one installed on the VM

**Comment by tomersagi** [comment]
hmmm, not very good. We'll need to back it up at some point.

**Comment by tomersagi** [comment]
The wikidata index is now loaded into the Elastic Search server on localhost. The name of the index is wd_202212.

![image](https://user-images.githubusercontent.com/8471397/205307093-4b9c34a6-a481-40a3-a0f7-062f39a0d590.png)

**Comment by tomersagi** [comment]
@kalycoding the ball is in your hands now.

**Comment by tomersagi** [comment]
I aliased the index as `wd`

**Comment by tomersagi** [comment]
![image](https://user-images.githubusercontent.com/8471397/215742553-205f74b9-2e31-4ab0-83d6-2719f4393293.png)
 
Then in this page select Wikidata reconciliation:

![image](https://user-images.githubusercontent.com/8471397/215742737-0b17a739-58d0-4d36-9899-fdd5c7b70a56.png)

Currently we get an error message:

![image](https://user-images.githubusercontent.com/8471397/215742832-51323101-ac7e-4186-a066-51585b21c414.png)
