### ISSUE TITLE
downloading BT does not work

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#100]
Neither tsv or Json.  an empty "undefined.html" appears in the downloads in either case with "Failed - No file".

**Comment by tomersagi** [comment]
I think I fixed it. @sinairusinek please check.

**Comment by sinairusinek** [comment]
(THIS IS THE SAME AS ISSUE 100)

**Comment by tomersagi** [comment]
Fixed

**Comment by tomersagi** [comment]
ok, this is a seperate issue. I am on it.
