### ISSUE TITLE
Encoding problem?

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#101]
I uploaded the following file that is utf-8 as dataset but the encoding on the screen of the Browsing panel doesn't look right:
<img width="673" alt="Screen Shot 2023-05-05 at 10 04 16" src="https://user-images.githubusercontent.com/4381316/236398847-2feba124-8406-4e1c-9c4e-67399ce9b5e5.png">
<img width="279" alt="Screen Shot 2023-05-05 at 10 04 04" src="https://user-images.githubusercontent.com/4381316/236398886-2031a281-6601-4ad0-8f9e-602c77c3263f.png">

**Comment by sinairusinek** [comment]
I see that the same problem happens with Karl's interface, so I'll write an email to both of you.

**Comment by sinairusinek** [comment]
I sent you Karl the file via email, it is Sinai_GIL2_20230504_164102-tsv (2).tsv,

**Comment by sinairusinek** [comment]
[Sinai_GIL2_20230504_164102-tsv (2).txt](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/11421624/Sinai_GIL2_20230504_164102-tsv.2.txt)

**Comment by tomersagi** [comment]
Hi, this looks fine in my interface. Are you sure about this?
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/7b8a2918-98dc-4b15-97d0-0f41d94e15a8)

https://tool.mehdie.org/datasets/211/summary

**Comment by tomersagi** [comment]
The problem seems to be localized to the symbol above the lamed:

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/ee71700b-300b-4c4f-8335-be5b54b9ab1a)

**Comment by tomersagi** [comment]
Can you identify the unicode code for this symbol for me?

**Comment by tomersagi** [comment]
ok, I enlarged it. This does not look like Hebrew to me: 
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/5110c2d1-c712-4ab4-8f11-9037de2395d8)

I cannot find the unicode symbol for this.

**Comment by sinairusinek** [comment]
True, this is Shada (unicode 0651 I think, or at least should be), https://en.wikipedia.org/wiki/Shadda. It is used here for transliteration of Judeo-Arabic names. 
Is this the source you asked for?
[view-source_https___tool.mehdie.org_datasets_211_browse.txt](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/11477233/view-source_https___tool.mehdie.org_datasets_211_browse.txt)

**Comment by tomersagi** [comment]
Yes, but it doesn't actually help me. Hmm, will think about it.

**Comment by tomersagi** [comment]
This is a snark, won't fix, no time for this.
