### ISSUE TITLE
Dataset download of LP-TSV

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#102]
<img width="469" alt="Screen Shot 2023-05-05 at 11 56 37" src="https://user-images.githubusercontent.com/4381316/236416756-f51015b3-4275-4e6e-853b-9e825539ecc9.png">
The "Linked Places Format" works well and downloads the JSON format, But the LP-TSV(Augmented) should download the TSV, enriched with the confirmed (same-as) links in the "matches" column.  The TSV can then be uploaded for another matching, leveraging the matches that were already made.

**Comment by tomersagi** [comment]
It seems the problem is that both links download the same JSON format, right @sinairusinek ?

**Comment by sinairusinek** [comment]
Something broke again: when trying to download the lp-tsv I get the url "https://home/macbookpro/whgazetteer-mehdie/media/downloads/Sinai_BT_20230511_050911.tsv" - and the notice: This site can’t be reached - Check if there is a typo in home.

**Comment by sinairusinek** [comment]
update:  when trying to download files now, clicking the link prompts something but then I get these notices in the bottom of the window (where downloaded files normally appear):
<img width="1286" alt="Screen Shot 2023-05-13 at 11 27 16" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/c31f38d7-ec18-4519-bae0-f901d4eeed21">

**Comment by tomersagi** [comment]
Yeah, it's strange. The files are available, but not downloading

**Comment by tomersagi** [comment]
Fixed, finally.
