### ISSUE TITLE
Stringify 'start' values during ingest

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#106]
A frequent type error is caused when trying to ingest a dataset that was exported from WHG, or Open Refine, where the numbers in the "start" column (which are 4 character date expressions) are set to number type. It would be very helpful if during the upload the type, if number, would be changed to string.
<img width="652" alt="Screen Shot 2023-05-13 at 11 40 45" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/38286751-fd9f-4a92-9e07-d649095734d9">

**Comment by tomersagi** [comment]
I need more details. Please provide a file that fails and give examples of rows that do not fail and those that do.
