### ISSUE TITLE
Dadaset deletion not possible

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#114]
The dataset "Lev-Places" has no deletion button. 
<img width="1146" alt="Screen Shot 2023-05-30 at 15 22 05" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/644cff4c-31e8-419a-9215-e54b444b6d95">
Compare:
<img width="703" alt="Screen Shot 2023-05-30 at 15 26 55" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/4d57b432-5f0e-4e46-8dbf-754cb727874b">

**Comment by tomersagi** [comment]
I did not find this dataset. Probably deleted...
