### ISSUE TITLE
Update in WHG

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#115]
Karl just corrected the WHG comment view to include both internal place ID and title (otherwise it's a guesswork to understand which record the comment relates to). This is what it looks like now:
<img width="1155" alt="Screen Shot 2023-05-30 at 15 41 21" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/a72c1ba9-f44d-4fe6-b27d-fb9ff0b19421">
compare:
<img width="756" alt="Screen Shot 2023-05-30 at 15 43 16" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/42e89039-6ee0-41f8-b41c-81cf35cdd990">

**Comment by tomersagi** [comment]
Fixed @sinairusinek
