### ISSUE TITLE
Description not showing in the matching interface

### ISSUE THREAD

**Issue by ElectricFrogy** [UHaifa-IS/whgazetteer-mehdie#124]
When trying to match between locations from two different datasets (Yaqut and Benjamin of Tudela), the descriptions for locations of the latter dataset are not showing. the Dataset of benjamin of Tudela was undoubtably uploaded with a description column. However, they are not showing. here as an image of the described issue:

![Sagi5](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/139448764/ccfbb08b-c19d-4d3e-89cd-da3fd71925ee)

On the right hand side, descriptions for locations are missing.

[Here is a link to the Benjamin of Tudela Dataset](https://tool.mehdie.org/datasets/257/browse)

**Comment by tomersagi** [comment]
Using this query verified that place id 109331 has a description:

```
select pd.* from place_description pd join places p on pd.place_id = p.id join datasets D on p.dataset = D."label" where D.id = 257 and pd.place_id = 109331;
```

On screen no description is shown:
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/8d3bda50-ab8e-4536-9809-f5cb539ce5ef)

**Comment by tomersagi** [comment]
URL is `review`

**Comment by tomersagi** [comment]
backend code is in `views.py `method `review`

**Comment by tomersagi** [comment]
Fixed: 
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/b39bf0f3-8b6e-42f9-80d4-dc78caec0e90)
