### ISSUE TITLE
matching fails

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#127]
Trying to match dataset 251 (Hasidic unrec) with dataset Zadikim fails with the following message:
Your ER reconciliation task has failed due to an error.
(['Expecting value: line 1 column 1 (char 0)'])

Your dataset matching task is being processed. Please wait a few minutes and refresh this page.
14:44 on september 19

**Comment by sinairusinek** [comment]
the same happens a minute later when I try to match against Fischer

**Comment by tomersagi** [comment]
Duplicate of #134 try again
