### ISSUE TITLE
matching done but fails to load in linking gui

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#129]
10:55 on 20.9 done on Yaqut dataset, linking with Tudela August:

<img width="1229" alt="Screen Shot 2023-09-20 at 10 55 45" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/d884a0da-4244-4648-b7a7-3f5d078eaf20">

**Comment by tomersagi** [comment]
Update the message from "a few minutes" to "up to an hour"

**Comment by tomersagi** [comment]
Fixed
