### ISSUE TITLE
dataset upload flawed

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#13]
When uploading a dataset the file is uploaded but no records or other details are registered.

**Comment by sinairusinek** [comment]
![WhatsApp Image 2022-11-18 at 1 29 25 PM (1)](https://user-images.githubusercontent.com/4381316/203502517-6bbd73a4-739f-4c83-ae50-43f46c676f22.jpeg)
![WhatsApp Image 2022-11-18 at 1 29 25 PM](https://user-images.githubusercontent.com/4381316/203502524-15824800-c094-4460-97c5-42f7cae7d172.jpeg)

**Comment by kalycoding** [comment]
![D2132DB2-401E-41FF-B9D5-281BF765B36F](https://user-images.githubusercontent.com/47900824/203530634-e6711168-2157-4c29-bb39-234a2e2c9a68.png)
![DB542A26-EAEC-48C1-AD84-A00676BFDF0F](https://user-images.githubusercontent.com/47900824/203530647-2276d6e9-79a8-4a86-9134-f4a5936f4a1f.png)

im not so sure… but the data was uploaded fine her

**Comment by tomersagi** [comment]
Yes, but only from your user. / machine. Try with Sinai's user or with her machine and see why it does not work for her. For me it does not work at all. For her it works partially, completing the upload but not actually loading the places.

**Comment by kalycoding** [comment]
dataset upload now works for all users

**Comment by tomersagi** [comment]
@kalycoding I have a message from you that this is fixed that seems to be deleted. What is the status here?

**Comment by kalycoding** [comment]
@tomersagi seems dataset upload problem is from gunicorn server, dataset upload works fine with django development server, ssh into the server and run ```python manage.py runserver 0.0.0.0:8000``` and try uploading the dataset,

**Comment by kalycoding** [comment]
i'm investigating what's causing the issue
