### ISSUE TITLE
Matches that are rejected in the linking process are nevertheless added to the results

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#132]
e.g when downloading Tudela matches like Yaqut:dig03683 - BJ5 are added even though we clicked "different"

**Comment by tomersagi** [comment]
In this page:
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/d80c0693-ea8f-4fa7-be8e-238958ee2588)

The two links that allow the download of the dataset in linked--places format and tsv format create a file that contains all matches and not only the approved ones.

**Comment by tomersagi** [comment]
The download link is generated by this code in ds_summary.html:_

`<p><a class="a-dl-celery" href="#" ref="tsv">LP-TSV (augmented) {% fontawesome_icon 'download'%}</a>
`

**Comment by tomersagi** [comment]
This is eventually handled by a celery task in *datasets/task.py* named *make_download*d

**Comment by tomersagi** [comment]
Fixed by changing the code that creates the list of matches to exclude those place_link records that contain a relation "different"
