### ISSUE TITLE
There is no way to view all matched/rejected matches

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#133]
In WHG one can filter in the browsling panel to see all items reviewed or non reviewed:

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/6ea407f6-56f7-4866-9fb4-ba420f8854b7)

It would be good to have this functioning. We need to add a mechanism to see matches that we did. The information is in the place_link table. This table has a set of links for some of the places (one place -> many place_links). The type of the link is in the `jsonb` field. External links are those whose type is "closeMatch". For example: {"type": "closeMatch", "identifier": "wd:Q31864504"}. Internal links are everything else except type "different". So for example: {"type": "same_as", "identifier": "Yaqut:dig03853"} is an internal link and  {"type": "different", "identifier": 33726} is not a link. 
- [ ] Remove the 'ccodes' column
- [ ] Add a column to the list of places called **External matches** that has a checkbox if the place is matched to external sources. 
- [ ] Add a column to the list of places called **Internal matches** that has a checkbox if the place is matched to other datasets in MEHDIE
- [ ] Add a column to the list of places called **Rejected matches** that has a checkbox if the place has matches that were rejected to other datasets in MEHDIE
- [ ] Add tool tips to explain these columns: External matches: "This field has a checkmark if the place is matched with external sources such as Wikidata and Geonames". Internal Matches: "This field has a checkmark if the place is matched with a place from at least one other dataset on MEHDIE."Rejected matches: "This field has a checkmark if the place was matched with a place from another dataset on MEHDIE and this match was rejected. 
- [ ] Change the mechanism for the filter above the table to show the following options: "All, has matches, has internal matches, has external matches, has rejected matches." Filter the table accordingly to show All, only those rows with checkmarks in the internal matches field, only those rows with checkmarks in the external matches field, only those with chekmarks in the rejected matches field.

**Comment by tomersagi** [comment]
For example, this place: 
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/dc5afb30-b781-40f7-8403-ca50541d1a97)

Was supposed to be matched with Yaqut and does not appear in the list of matches.

**Comment by tomersagi** [comment]
Resolved in another way
