### ISSUE TITLE
dataset stuck in pseudo accession stage

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#134]
Having tried running linking with Wikidata for the dataset 'Hasidic unrec' , the result came as 0 and I got the following message:
<img width="1180" alt="Screen Shot 2023-09-20 at 14 13 49" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/df409bbd-dc2b-4489-bedf-3d00a79d5b47">

**Comment by tomersagi** [comment]
@sinairusinek As it states, there are no hits for the matching with wikidata. Do you want me to investigate why there were no hits? Or something else?

**Comment by sinairusinek** [comment]
I deleted the set, re-uploaded it and tried to run matches. The first try, nothing happened. Now (11:23, 17.10.23), more than an hour later, I tried again (dataset 260). This is what happens:


<img width="973" alt="Screen Shot 2023-10-17 at 11 22 34" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/b56acd07-0b11-41fc-a71d-36b00ba96e21">

**Comment by tomersagi** [comment]
Problem is coming from the prepare service rejecting the request from the main ER service:

`requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://mehdi-er-compare-snlwejaxvq-ez.a.run.app/process`

**Comment by tomersagi** [comment]
Should be solved, try again in 10 minutes.

**Comment by sinairusinek** [comment]
this is from this morning: tried two matches, the first never came through, the second (with another dataset) returned an error:
<img width="1161" alt="Screen Shot 2023-10-26 at 10 34 08" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/5ef1280c-d128-4f5a-aef3-685c240ac053">

**Comment by tomersagi** [comment]
Investigating

**Comment by tomersagi** [comment]
I think this is resolved. @sinairusinek ?
