### ISSUE TITLE
Link to view deferred matches not fuctioning

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#135]
When clicking on the 'deferred' option in the linking page (of any dataset):

<img width="749" alt="Screen Shot 2023-09-26 at 11 39 39" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/f0a51cfe-c313-4595-b036-fe9dc43c429a">

- I am led to the list of all matches, not just deferred, even though it says 'deferred' in the title (see the number of results)

<img width="780" alt="Screen Shot 2023-09-26 at 11 39 47" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/53b039d7-cbfc-423c-be52-539d4662dd78">

**Comment by tomersagi** [comment]
Checking gunicorn log.

**Comment by tomersagi** [comment]
Seems that the page is rendered as Defferred (see line 23 in review.html) but the recordset is the wrong one. The recordset comes from the context object sent to review.html. Need to check its creation.

**Comment by tomersagi** [comment]
Problem is here:

```
# calling link passnum may be 'pass*', 'def', or '0and1' (for idx)
    # if 'pass*', just get place_ids for that pass
    if passnum.startswith('pass'):
        pass_int = int(passnum[4])
        # if no unreviewed left, go to next pass
        passnum = passnum if cnt_pass > 0 else 'pass' + str(pass_int + 1)
        hitplaces = Hit.objects.values_list('place_id', flat=True).filter(
            task_id=tid,
            reviewed=False,
            query_pass=passnum
        )
    else:
        # all unreviewed
        hitplaces = Hit.objects.values_list('place_id', flat=True).filter(task_id=tid, reviewed=False)

    # set review page returned
    if auth in ['whg', 'idx']:
        review_page = 'accession.html'
    else:
        review_page = 'review.html'
```

**Comment by tomersagi** [comment]
We have a problem. The Defferal is represented by a 2 value in the review_wd / review_tgn / review_whg columns of the place table. This does not jive with the 1:n aspect of MEHDIE matches.

**Comment by tomersagi** [comment]
When pressing "defer" in the review screen, the correct behavior is that the flag field in the hits table gets marked for all hits that do not have a relation assigned to them. 
- [ ] apply this behavior in the review screen
- [ ] change the defer count code to count unique place ids with flags in the hits table
- [ ] change the filter loading the review screen when pressing on defer to check for existence in the hits table with a flag.
