### ISSUE TITLE
linking task fails

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#138]
Attempted linking AlThurayyaTry with Yaqut just now gave an error:
<img width="443" alt="Screen Shot 2023-10-29 at 12 42 41" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/45d3cfae-b8fa-42ff-b244-3d65d38f058f">

**Comment by tomersagi** [comment]
Increased the memory size, failed due to memory limit reached. Please try again.

**Comment by tomersagi** [comment]
@sinairusinek assuming this is fixed
