### ISSUE TITLE
Linking screen interface design

### ISSUE THREAD

**Issue by MoranZaga** [UHaifa-IS/whgazetteer-mehdie#142]
If possible, please change the matchboxes according to the following sketch:

1. split to two columns 
2. Move: **Variants**, **Types** and **Parents**, **Eariest/latest** to the right column
3. define fixed 5 lines of description and scrolling option beyond 5 lines

Thanks,
Moran

**Comment by tomersagi** [comment]
Done 1 and 2

**Comment by MoranZaga** [comment]
Is it possible to define fixed 5 lines of description and scrolling option beyond 5 lines? It can make the reading&matching process easier and friendly-ier.

**Comment by tomersagi** [comment]
This task should be done in the review screen:
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/44833aac-9afc-4ca0-a8d7-f8d5fa65dd2c)

Notice that the description appears in both the left side place and in the list of matched places for each matched place. Both text boxes should behave as Moran described.
