### ISSUE TITLE
Mehdie full UPLOAD fails 

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#143]
'utf-8' codec can't decode byte 0xd9 in position 65535: unexpected end of data

the file:
[Uploading YaqutLP_ALL_November_01.txt…]()

the error
Environment:

Request Method: POST
Request URL: https://tool.mehdie.org/datasets/create/

Django Version: 2.2.28
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.gis',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'bootstrap_modal_forms',
 'captcha',
 'celery_progress',
 'django_celery_results',
 'django_extensions',
 'django_filters',
 'django_resized',
 'django_tables2',
 'djgeojson',
 'fontawesome',
 'guardian',
 'leaflet',
 'mathfilters',
 'multiselectfield',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_datatables',
 'rest_framework_gis',
 'tinymce',
 'accounts.apps.AccountsConfig',
 'api.apps.ApiConfig',
 'areas.apps.AreasConfig',
 'collection.apps.CollectionConfig',
 'datasets.apps.DatasetsConfig',
 'elastic.apps.ElasticConfig',
 'main.apps.MainConfig',
 'places.apps.PlacesConfig',
 'remote.apps.RemoteConfig',
 'resources.apps.ResourcesConfig',
 'search.apps.SearchConfig',
 'traces.apps.TracesConfig']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.security.SecurityMiddleware']

Traceback:

File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/django/views.py" in sentry_wrapped_callback
  87.                 return callback(request, *args, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/django/contrib/auth/mixins.py" in dispatch
  52.         return super().dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/django/views/generic/edit.py" in post
  172.         return super().post(request, *args, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/django/views/generic/edit.py" in post
  142.             return self.form_valid(form)

File "/usr/lib/python3.9/contextlib.py" in inner
  79.                 return func(*args, **kwds)

File "/home/macbookpro/whgazetteer-mehdie/datasets/views.py" in form_valid
  2233.                         raise e

File "/home/macbookpro/whgazetteer-mehdie/datasets/views.py" in form_valid
  2230.                             file_out.write(chunk.decode("utf-8"))

Exception Type: UnicodeDecodeError at /datasets/create/
Exception Value: 'utf-8' codec can't decode byte 0xd9 in position 65535: unexpected end of data

**Comment by tomersagi** [comment]
The problem is that the chunking of the file may cause a UTF character to be split in the middle and misread. 
I implemented a binary read and write in the current position. If this problem returns in other parts of the code we will need to implement a chunkless reading  of these files.

**Comment by tomersagi** [comment]
Resolved
