### ISSUE TITLE
Linking review not taking effect

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#145]
When reviewing match results, selecting a same-as and saving does not have any effect.

**Comment by tomersagi** [comment]
The problem is that the formset is failing validation with the following error:

```
 [DEBUG] entered POST for review page, place_id: 107727, review_status: None
Nov 07 16:53:27 mehdie-gui gunicorn[101946]: Review Status is None, value of review_status==1 is False and value of formset.is_valid is False
Nov 07 16:53:27 mehdie-gui gunicorn[101946]: [DEBUG] formset is not valid
Nov 07 16:53:27 mehdie-gui gunicorn[101946]: <ul class="errorlist"><li>authority<ul class="errorlist"><li>Select a valid choice. 241 is not one of the available choices.</li></ul></li></ul>
```

This is possibly because we are trying to record the other dataset ID somewhere that is not designed for this in the Django system.

**Comment by tomersagi** [comment]
Fixed by removing the validation over the authority field to be from a list of authorities since we now use this field to list datasets.

**Comment by MoranZaga** [comment]
הבעיה היא שבלחיצה על אחת מהאפשרויות בתפריט הדרופ-דאון הוא מוביל למסך שגיאה

**Comment by tomersagi** [comment]
problem is traced to the fact that the authority field in the hits table has the string 'md' in it instead of the dataset id for the task (in this case 256). 

- [ ] update the hits table to set that tuhority field to 256 for this task
- [ ] update the hits table for all hits with 'md'
- [ ] Find the code that updates the 'md' in the authority field and update it to put the dataset_2 value (from the task table, for example for this task: {'dataset_id': 229, 'dataset_2': '256', 'csv_url': 'https://storage.googleapis.com/mehdie_er/output_611773d8-5c27-4604-8f16-30029b5f24da.csv', 'aug_geom': 'on', 'lang': 'en', 'user': 11, 'tsv_url': 'https://storage.googleapis.com/mehdie_er/output_611773d8-5c27-4604-8f16-30029b5f24da.csv'}

**Comment by tomersagi** [comment]
Code was updated October 30th. The problem hits where created on October 29th so the problem is already solved.
