### ISSUE TITLE
Bug: IndexError screen

### ISSUE THREAD

**Issue by MoranZaga** [UHaifa-IS/whgazetteer-mehdie#147]
YaqutFull > Damast task: After several matching (Reconciliation) reviews an error screens appears: IndexError list index out of range. Later, going back to the main Reconciliation Tasks page, the IndexError list index out of range page appears again after clicking the "review" button. 

YaqutFull > Aladag: Ditto 

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/48962654/68b7f67a-c7f8-44ff-b405-5c2ff2a10c7a)
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/48962654/7d65cb1d-875e-4383-a372-456e55808790)

**Comment by tomersagi** [comment]
Fixed maybe. Please try now.
