### ISSUE TITLE
Missing description 

### ISSUE THREAD

**Issue by MoranZaga** [UHaifa-IS/whgazetteer-mehdie#148]
Missing description in some places on the left bar

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/48962654/5e159184-1f95-4d29-8d10-47eea2a58e4f)

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/48962654/86901d18-b4f9-4e18-96f5-d73d5023e3c4)

**Comment by tomersagi** [comment]
Is this still an issue Moran?

**Comment by tomersagi** [comment]
No description in the data from these places.
