### ISSUE TITLE
Matching task does not arrive

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#149]
During Moran and my meeting on Wednesday (Dec. 26) we sent a couple of matching tasks. The first never arrived, the others appeared as pending, but eventually never arrived either. Today (friday Dec. 29) around midday I tried again - a relatively small matching task between Kima-PS and Aladag. About two hours later, It did not arrive yet.

**Comment by tomersagi** [comment]
It could be fixed now. Try again.
