### ISSUE TITLE
After ER is done, update the reconciliation page to show the result.

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#15]
After ER is done, update the linking tab to show the task result as is done for wikidata reconciliation. This is how it looks in WHG:

![image](https://user-images.githubusercontent.com/8471397/203534933-cd891846-8f52-4ca4-9a8b-7cae9480b8c6.png)

Pressing on 'review' should send the user to the review page (see issue #16 ).

**Comment by kalycoding** [comment]
![Screenshot 2022-11-27 at 12 45 58](https://user-images.githubusercontent.com/47900824/204133554-79ef073f-91b3-4dd1-91c5-73a178c9e5c5.png)

**Comment by tomersagi** [comment]
@kalycoding, this is insufficient. The review process must be tracked in the same way as the current review process. Use the same mechanism. You can add a download link in addition, but we need the review process to be supported here as well.

**Comment by kalycoding** [comment]
review process? i dont understand, pls elaborate more

**Comment by tomersagi** [comment]
![Skærmbillede 2022-11-29 153412](https://user-images.githubusercontent.com/8471397/204557277-f0111735-f241-4724-af07-af5cec6252ba.png)

@kalycoding, when the user performs a reconciliation task, each place record in the user's dataset is compared against wikidata (old system) or another dataset (our new system). For each record, either a set of matches are found or not. Each record needs to be reviewed by the user together with its matches (see issue #16 ). The WHG system already has a mechanism to track this review process by the user and a GUI (see marked in yellow above). You need to read our algorithm's results that you receive as a CSV and update this screen in the same way. How many records were matched, then we start out with all of them waiting to be reviewed, and when the user reviews them ( in the screen in #16 ), this number is updated. All of this mechanism already exists in WHG, you just need to update it with the data returned from the ER service .

**Comment by tomersagi** [comment]
Done
