### ISSUE TITLE
Missing PARENT on the left bar

### ISSUE THREAD

**Issue by MoranZaga** [UHaifa-IS/whgazetteer-mehdie#168]
Hi, it seems like we're missing the "parent" field on the left bar. Can you please add it?
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/48962654/efd5ebbd-e760-47ad-a171-63fa04a7dade)

**Comment by tomersagi** [comment]
This will be fixed when the left bar is replaced with the one we have on the browse page.

**Comment by tomersagi** [comment]
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/7354538d-11f5-4d6c-b11b-2bf5c6f06b75)

**Comment by MoranZaga** [comment]
Cool. When will we be able to see it?

**Comment by tomersagi** [comment]
You can see it in the browse screen. It will be changed by Zarif during the week so that the review screen is identical to the browse screen.
