### ISSUE TITLE
Wrong doubled location 

### ISSUE THREAD

**Issue by MoranZaga** [UHaifa-IS/whgazetteer-mehdie#169]
For some reason, some entries with a single XY coordinates appear in two different places. Here's one example from dataset: Yaqut_Sham

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/48962654/9cbd311f-0f5e-41b9-90ee-6deeee869c27)

**Comment by tomersagi** [comment]
Related to #173

**Comment by tomersagi** [comment]
Fixed by #173
