### ISSUE TITLE
Corrections to Tudela 

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#177]
1. In the following [list](https://docs.google.com/spreadsheets/d/1pYtCQ1DPTE4FLMoEst_GSk9-GkO0_wQkP_v4LpObJxY/edit?usp=sharing) I put all places which had their coordinates deleted, wrongly added or wrongly replaced. 
2. pid 109404 wouldn't open from the browse window (and has wrong coordinates, maybe also matches). Console: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tomersagi** [comment]
Tudal corrections done

**Comment by tomersagi** [comment]
pid 109404 is now fixed.

**Comment by sinairusinek** [comment]
Sorry, after further inspection of the map I see three errors in coordinates:
109220 - remove coordinates
109293 - update coordinates to lat  38.1157, lon 13.3613
109333  - update coordinates to lat 41.008333,  lon 28.98
109374 - add coordinates  lat 31.853333, lon 35.0325 
Thanks!

**Comment by sinairusinek** [comment]
Another correction:  109177  Lat 29.841900, Lon 31.334200

**Comment by tomersagi** [comment]
@sinairusinek 109293 is Palermo https://www.wikidata.org/wiki/Q18440009 . How does lat 38.1157, lon 13.3613 work with that?

**Comment by tomersagi** [comment]
removed

60291	K15135	{"type": "Point", "citation": {"id": "match_data:dig07641", "label": "WHG"}, "coordinates": [37.211131, 36.28865]}	905e7ef6-800e-44e2-b383-a456527a9be9	POINT (37.211131 36.28865)	2023-09-20 10:02:34		109177

**Comment by sinairusinek** [comment]
And another correction: remove all of the links and coordinates for 109178 and 109186 . I already corrected this before but I guess it was added again by one of the evil tests.

**Comment by tomersagi** [comment]
> And another correction: remove all of the links and coordinates for 109178 and 109186 . I already corrected this before but I guess it was added again by one of the evil tests.

Removed this geom added in August 2023:

58412	K15288	{"type": "MultiPoint", "coordinates": [[35.65, 34.116666666667]]}		MULTIPOINT ((35.65 34.116666666667))	2023-08-28 16:55:15		109178

Are you sure about 109178? It has lots of closeMatch links which come from the source data usually:

49550	K15288	{"type": "closeMatch", "identifier": "viaf:236822589"}				2023-08-28 16:55:15	109178
49549	K15288	{"type": "closeMatch", "identifier": "gnd:4091275-9"}				2023-08-28 16:55:15	109178
49548	K15288	{"type": "closeMatch", "identifier": "wd:Q173532"}				2023-08-28 16:55:15	109178
49547	K15288	{"type": "closeMatch", "identifier": "wp:גבל"}				2023-08-28 16:55:15	109178
49546	K15288	{"type": "closeMatch", "identifier": "https://data.geo-kima.org/Place/15288"}				2023-08-28 16:55:15	109178
49545	K15288	{"type": "closeMatch", "identifier": "wp:Byblos"}				2023-08-28 16:55:15	109178
49544	K15288	{"type": "closeMatch", "identifier": "gn:273203"}				2023-08-28 16:55:15	109178

**Comment by tomersagi** [comment]
@sinairusinek are you sure about the place links for 109186?

**Comment by sinairusinek** [comment]
I tried to simplify, but can write exactly which are the wrong and right ones if it is preferable:
1. remove viaf:236822589, wd:Q173532, wp:גבל, wp:Byblos from 109178 and add them as matches to 109186
2.  remove  gnd:4091275-9 https://data.geo-kima.org/Place/18052  and gn:273203 from 109186 and add them as matches to 109178 (when they are not there already)

**Comment by sinairusinek** [comment]
No, I'm afraid it is still a mess. I guess I can fix the matches with Yaqut, but regarding the rest, please:

id	src_id	jsonb	task_id	review_note	black_parent	created	place_id
49544	K15288	{"type": "closeMatch", "identifier": "gn:273203"}				remove - false!! 
49549	K15288	{"type": "closeMatch", "identifier": "gnd:4091275-9"}				remove - false!!
49546	K15288	{"type": "closeMatch", "identifier": "[https://data.geo-kima.org/Place/15288"}] this is correct
49584	K18052	{"type": "closeMatch", "identifier": "[https://data.geo-kima.org/Place/18052"}] this is correct
49587	K18052	{"type": "closeMatch", "identifier": "viaf:236822589"}				remove, redundant
49548	K15288	{"type": "closeMatch", "identifier": "wd:Q173532"}				this is correct
49585	K18052	{"type": "closeMatch", "identifier": "wd:Q173532"}				remove - false!!
49545	K15288	{"type": "closeMatch", "identifier": "wp:Byblos"}				this is correct
49547	K15288	{"type": "closeMatch", "identifier": "wp:גבל"}				remove (no such wp)
50731	K18052	{"type": "same_as", "identifier": "256:108293"}	 this is correct
50782	K18052	{"type": "same_as", "identifier": "256:108293"}	correct - but why does it appear twice?

**Comment by tomersagi** [comment]
The last two are from two separate matching tasks. I prefer keeping both for backwards compatibility. 
The rest are updated
