### ISSUE TITLE
bug - blocked links between elements in the browse view

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#197]
https://tools.mehdie.org/datasets/257/browse 
Clicking some place in the table, like 109303, opens both the place on the map and the info and graph below, but some places like 
109161 (tripoli) do not open the info and graph.  Also, when cilcking on the dot in the map the info would not open.

**Comment by tomersagi** [comment]
Problem stems from the fact that some links are null and don't have a valid identifier. 
These can be found using this query: `SELECT * FROM place_link WHERE "jsonb"->>'type' is null`

**Comment by tomersagi** [comment]
Fixed
