### ISSUE TITLE
Fix migration issues

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#2]
I will add here tasks as I go through the website and check it out
- [x] images are not showing 
- [x] Can't register because the captcha field is not working:
![image](https://user-images.githubusercontent.com/8471397/194877441-88e3b207-a3a0-4194-a62b-08145b90f1a0.png)
- [x] Can't log in with registered user. I tried using an active user in the database and logging in, and I got sent back to the login page:
![image](https://user-images.githubusercontent.com/8471397/194877941-4acb04af-44cb-4782-a84d-918cc3fcca8d.png)
![image](https://user-images.githubusercontent.com/8471397/194878020-c1da8150-4f3f-4eca-9cc8-dbcc610c0f1c.png)

**Comment by kalycoding** [comment]
i couldn't reproduce login bug

**Comment by tomersagi** [comment]
- [ ] Dataset upload screen is not working

http://34.91.171.131/datasets/create/

Uploading a tsv file results in a 500 error. Here is a TSV file that works on the original WHG website. 

[kima-as-in-WHGJuly2021.zip](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/9762844/kima-as-in-WHGJuly2021.zip)

**Comment by tomersagi** [comment]
- [ ] registration validation email contains the wrong link and is sent from example.com
![image](https://user-images.githubusercontent.com/8471397/195422293-18e53e34-be1f-497b-9ab6-8c54c4f12635.png)

**Comment by kalycoding** [comment]
> * [ ]  Dataset upload screen is not working
> 
> http://34.91.171.131/datasets/create/
> 
> Uploading a tsv file results in a 500 error. Here is a TSV file that works on the original WHG website.
> 
> [kima-as-in-WHGJuly2021.zip](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/9762844/kima-as-in-WHGJuly2021.zip)

looks like the error is coming from celery, celery is not running

**Comment by tomersagi** [comment]
What does that mean?

**Comment by kalycoding** [comment]
> What does that mean?

i clone the project locally and fixing it now

**Comment by tomersagi** [comment]
When logging in from tool.mehdie.org the screen does not respond and returns to the default empty screen.
- [ ] Fix login bug
- [ ] Allow login from https as well

**Comment by tomersagi** [comment]
- [ ] fix: contact-us page is not working

![image](https://user-images.githubusercontent.com/8471397/197980501-523dcdd9-89ed-4ce7-89e7-55a249b39fef.png)

**Comment by tomersagi** [comment]
- [ ] Fix: about page is not working:

![image](https://user-images.githubusercontent.com/8471397/197980730-0d5caa2e-56ed-4fe9-84e0-1fac5ec9c816.png)
