### ISSUE TITLE
Dataset upload gives 500 result

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#5]
Tried to upload the attached dataset. Got a 500 page with no explanation of what failed. 

![image](https://user-images.githubusercontent.com/8471397/199002376-1e509cca-7d62-4204-b308-1cc5e34a56c2.png)

[Yaqut-Andalusia_N_Africa.zip](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/9900788/Yaqut-Andalusia_N_Africa.zip)

- [ ] look at the logs and see why it failed.
- [ ] make sure the error is presented in an intelligent way to the user next time.

**Comment by kalycoding** [comment]
is datasets upload working on tools.mehdie?

also can you share me a link that's dataset upload working?

**Comment by tomersagi** [comment]
> 

No, it isn't. It works on the original website: https://www.whgazetteer.org/

**Comment by kalycoding** [comment]
i got it, i will resolve it soon

**Comment by kalycoding** [comment]
hi, i think the code working on whgazetter com is not the updatead version in their github

been debugging the code since morning

i hardcorded some data from the codebase just to make dataset upload works

we might hop on a call/meeting so you explain some stuffs to me

try uploading a dataset now and see

**Comment by tomersagi** [comment]
Still not working. Try with the attached dataset. This was tested on WHG this morning and worked. 
[Sinai_bt4_20221102_070054.zip](https://github.com/UHaifa-IS/whgazetteer-mehdie/files/9918308/Sinai_bt4_20221102_070054.zip)

**Comment by tomersagi** [comment]
Tried that now. Did not work either.
