### ISSUE TITLE
testing linking

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#67]
- I tried reconciliation with WD. After a couple of minutes I get an email notice:
 Greetings, Sinai Your Wikidata reconciliation task for the BT1 dataset has completed with status: SUCCESS. 96 records got a total of 133 hits. View results on the 'Reconciliation' tab (you may have to refresh the page). -- only there is no "Reconciliation" tab, and if the intention was the "linking" tab (which is how it is called in WHG) - then I don't see any results there. 

- I tried reconciling two datasets (Damast and BT, so not large ones!). Clicking "start" keeps the start button in highlight and the job seems to run, but then you are taken back to an empty linking panel. No email in this case.
- @zarifbekturdiev

**Comment by zarifbekturdiev** [comment]
@sinairusinek please can you take a look this task's result, I've done some changes

**Comment by sinairusinek** [comment]
Hi @zarifbekturdiev ! The WD works well, I experimented with the review and it looks good - except,  the WD results seem to be displayed in Russian- Is there a way to localise the presentation language or enable selection? If not, it is not ideal but preferable to make the presentation language English.
As to the dataset to dataset linking - I am still not getting any email, but after refreshing I am seeing the results in the linking page - but  without the coordinates of the target set - so the results do not appear on the map and the flash map marker doesn't work. 
<img width="655" alt="Screen Shot 2023-02-20 at 19 15 42" src="https://user-images.githubusercontent.com/4381316/220168147-58321ae0-bb84-4929-9677-c76c004d650d.png">

**Comment by zarifbekturdiev** [comment]
1 I didn't really understand where exactly it is shown in Russian, can you please make a screen
2 Binding datasets is another task (task #15) I'm still working on it,  I haven't enabled sending SMS to mail yet, flash map, the task is quite large while I'm working on it

**Comment by sinairusinek** [comment]
1. I was referring to the Wikidata preferred title and description, but right now when I went in to take a screenshot it is in English, so OK!

**Comment by zarifbekturdiev** [comment]
If everything is ok, you can close this task.
