### ISSUE TITLE
infobox missing in the browse panel

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#69]
<img width="735" alt="Screen Shot 2023-02-15 at 9 17 45" src="https://user-images.githubusercontent.com/4381316/218958795-41bcff1e-d3e3-4bae-a55d-36673ae49b46.png"><img width="989" alt="Screen Shot 2023-02-15 at 9 15 55" src="https://user-images.githubusercontent.com/4381316/218958804-88fa75b9-1245-47bb-a21f-2c36cbcb11ee.png">

**Comment by sinairusinek** [comment]
@zarifbekturdiev see the difference between whg and the Mehdie tool

**Comment by zarifbekturdiev** [comment]
Check, please @tomersagi

**Comment by tomersagi** [comment]
Looks great.
