### ISSUE TITLE
Add confidence score and explanation from the match result to the reconciliation review screen. 

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#70]
- [x] Add the confidence value with max 2 decimal places
- [x] Add the explanation field as a scrollable text box

**Comment by sinairusinek** [comment]
<img width="964" alt="Screen Shot 2023-02-15 at 9 30 06" src="https://user-images.githubusercontent.com/4381316/218961324-4b163579-3f2b-4f3e-9e2b-3884004a7afa.png">

**Comment by tomersagi** [comment]
Done.
