### ISSUE TITLE
The title of the target dataset has to appear in the linking screen

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#79]
The first task in this screen is matching the BT dataset with the dataset titled "Damast" - the title has to appear on the screen. It can appear either next to the dataset ID on the left, or on the right, where the WD icon appears in the second task.
<img width="1164" alt="Screen Shot 2023-02-24 at 10 18 37" src="https://user-images.githubusercontent.com/4381316/221127979-a3a429be-93c5-4d2f-ba12-98522a34c775.png">

**Comment by tomersagi** [comment]
Works well:
![image](https://user-images.githubusercontent.com/8471397/223389096-8904e423-2130-4baa-b0ec-b217318df3a9.png)
