### ISSUE TITLE
Location markers for matched places do not appear on map many times in review screen

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#80]
In this screen:

![image](https://user-images.githubusercontent.com/8471397/222709014-5c4bcbb9-637a-4b0a-ab0a-72473c6a6d4d.png)

The places on the right-hand side should appear as green dots on the map and flash when the flash marker is touched. This does not happen for most results. @sinairusinek can perhaps provide concrete screen shots showing this.

**Comment by sinairusinek** [comment]
To be more specific:
green dots represent the coordinates given in the source dataset, if they are there. The yellow dots represent the candidate matches in the left.  When clicking on the yellow globe of each match, the corresponding dot on the map should flash, and vice versa. 
<img width="563" alt="Screen Shot 2023-03-06 at 20 01 45" src="https://user-images.githubusercontent.com/4381316/223193087-ac822bd7-2e01-406c-8011-35426c551412.png">

**Comment by sinairusinek** [comment]
here is what happens when I click a dot on the map:
<img width="852" alt="Screen Shot 2023-03-06 at 20 04 32" src="https://user-images.githubusercontent.com/4381316/223193653-dd8784ee-d075-4d3d-a241-dc971a5d29d0.png">
