### ISSUE TITLE
notes do not open in review

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#90]
When clicking "add note" the screen darkens but no window or pop up appears. 
<img width="328" alt="Screen Shot 2023-03-14 at 15 56 38" src="https://user-images.githubusercontent.com/4381316/225024255-3da0154e-7edc-4046-af50-7080bae053cc.png">

**Comment by zarifbekturdiev** [comment]
@tomersagi Hi please check

**Comment by sinairusinek** [comment]
checked! it works now. thanks!
