### ISSUE TITLE
remove/change size limit in upload

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#96]
Trying to upload Himme (5.2MG) gave this error. Our largest dataset is over 5 mb, but it can be divided to parts. Himme, however, is just over 2 and it would be good to upload it as a whole, and we've seen that there is no problem to run the matching on it. 

![WhatsApp Image 2023-04-19 at 5 30 42 PM](https://user-images.githubusercontent.com/4381316/233287914-73dfe12f-df11-4d7e-97ed-453f1dd98874.jpeg)

**Comment by tomersagi** [comment]
I tried reviewing the logs `sudo journalctl --unit=gunicorn >> ~/log.txt` . The error seems unrelated (see  #97 ).

**Comment by tomersagi** [comment]
Some further digging with the assistance of ChatGPT narrowed it down to the NGINX configuration. The default there is 1MB. I added `client_max_body_size 25M;` in the HTTP block of the `/etc/nginx/nginx.conf` file.
@sinairusinek please test this fix.
