### ISSUE TITLE
matching with a large dataset doesn't work?

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#98]
Tried to match BT and Himme Yesterday, on Saturday 29.4. through Mehdie tool. The wheel turned but nothing is visible in the linking (nor did I get any message about it)

**Comment by sinairusinek** [comment]
Correction: matching ANY dataset to another (not to WD) doesn't work! it is not a matter of size.

**Comment by sinairusinek** [comment]
update: now I did manage to match Al Thurayya and BT, but no success with Himme yet. Might be a size issue? but also, the button simply doesn't seem to respond and there is no notice about the matching ongoing or failing as it should be.

**Comment by tomersagi** [comment]
Update; I found no error in the celery log from these dates.

**Comment by sinairusinek** [comment]
16:21 Israel time, I tried again to link BT to Himme. 
Having pressed the start button. the screen gets stuck in this condition, and the spinner on the chrome tab spins:
<img width="638" alt="Screen Shot 2023-05-08 at 16 22 23" src="https://user-images.githubusercontent.com/4381316/236835623-08044685-9dc3-4dae-8cb7-8523f24e3b89.png">
16:26 I get 504 Gateway Time-out.

**Comment by tomersagi** [comment]
Seems to work for smaller matching processes - BIT-DAMAST and HIMME-HAsidic

**Comment by tomersagi** [comment]
We did what we can. Large datasets work, huge datasets do not.
